HOSTS:
  centos-7:
    vmname: centos-7-us-east-1
    platform: el-7-x86_64
    hypervisor: ec2
    amisize: t2.small
    snapshot: foss
    user: centos
CONFIG:
  type: foss
  log_level: verbose
  masterless: true
